/*
 * Copyright (c) 2022 See AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.tommyettinger.textra;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.PixmapIO;
import com.badlogic.gdx.graphics.glutils.ShaderProgram;

import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * An unusual runnable; this "stamps" font textures with a small white square in the lower-right corner, and makes
 * the corresponding .fnt file reference the given white block as its solid block char. This is used by the box-drawing
 * glyph generation code, and also can be used to draw connecting underlines and strikethrough lines.
 * <br>
 * This is only needed for .fnt files. The .json(.lzma) files generated by FontWriter already place a white block in
 * their images automatically.
 */
public class BlockStamper  extends ApplicationAdapter {
    public static void main(String[] args) {
        Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
        config.setTitle("Block Stamper Tool");
        config.setWindowedMode(800, 400);
        config.disableAudio(true);
        ShaderProgram.prependVertexCode = "#version 110\n";
        ShaderProgram.prependFragmentCode = "#version 110\n";
        config.useVsync(true);

        args = new String[]{"src/test/resources/unicode/LanaPixel.fnt"};

        new Lwjgl3Application(new BlockStamper(args), config);
    }

    private final String[] parameters;
    private PixmapIO.PNG png;

    public BlockStamper(String[] args) {
        if(args == null || args.length == 0){
            parameters = null;
            System.out.println("Not given any inputs; exiting.");
            System.exit(0);
            return;
        }
        parameters = args;
    }

    @Override
    public void create() {
        png = new PixmapIO.PNG();
        png.setFlipY(false);
        if(parameters != null) {
            for (String name : parameters) {
                FileHandle fh = Gdx.files.local(name);
                if (fh.exists())
                    update(fh);
                else {
                    fh = Gdx.files.absolute(name);
                    if (fh.exists())
                        update(fh);
                }
            }
        }
        Gdx.app.exit();

    }
    public void update(FileHandle fnt) {
        FileHandle[] children = fnt.parent().list((dir, name) -> name.equals(fnt.nameWithoutExtension() + ".png"));
        PER_CHILD:
        for(FileHandle fh : children) {
            System.out.println("Operating on " + fh.name());
            Pixmap pm = new Pixmap(fh);
            int w = pm.getWidth(), h = pm.getHeight();
            PER_ROW:
            for (int row = h - 1; row >= 3; row--) {
                for (int col = 0; col < w; col++) {
                    int color = pm.getPixel(col, row - 3);
                    if (!((color & 0xFF) == 0 || (color >>> 8) == 0)){
                        break PER_ROW;
                    }
                }
                h--;
            }
            for (int x = w - 3; x < w; x++) {
                for (int y = h - 3; y < h; y++) {
                    int color = pm.getPixel(x, y);
                    if(color == -1) {
                        System.out.println("Already stamped " + fh.name());
                        continue PER_CHILD;
                    }
                }
            }
            pm.setColor(-1);
            pm.fillRectangle(w - 3, h - 3, 3, 3);
            try {
                png.write(fh, pm);
                new TransparencyProcessor(new String[]{fh.path()}).rewrite(fh);
            } catch (IOException e) {
                System.out.println("Had a file IO problem with " + fh.name());
                e.printStackTrace();
            }
            if (fnt.exists()) {
                String text = fnt.readString("UTF-8");
                if (text.contains("char id=9608 ")) {
                    fnt.writeString(text.replaceFirst(
                                    "char id=9608 .+", "char id=9608 x=" + (w - 2) + " y=" + (h - 2) + " width=1 height=1 xoffset=0 yoffset=0 xadvance=1 page=0 chnl=15"),
                            false, "UTF-8");
//                } else if (text.contains("char id=0 ")) {
//                    fnt.writeString(text.replaceFirst(
//                                    "char id=0 .+", "char id=9608 x=" + (w - 2) + " y=" + (h - 2) + " width=1 height=1 xoffset=0 yoffset=0 xadvance=1 page=0 chnl=15"),
//                            false, "UTF-8");
//                } else if (text.contains("char id=-1 ")) {
//                    fnt.writeString(text.replaceFirst(
//                                    "char id=-1 .+", "char id=9608 x=" + (w - 2) + " y=" + (h - 2) + " width=1 height=1 xoffset=0 yoffset=0 xadvance=1 page=0 chnl=15"),
//                            false, "UTF-8");
                } else {
                    Matcher cc = Pattern.compile("chars count=(\\d+)").matcher(text);
                    if(!cc.find()){
                        throw new RuntimeException(".fnt file isn't valid: " + fnt.path());
                    }
                    fnt.writeString(text.replaceFirst(
                                    "chars count=\\d+(\\R)", "chars count=" + (Integer.parseInt(cc.group(1)) + 1)
                                            + "$1char id=9608 x=" + (w - 2) + " y=" + (h - 2) + " width=1 height=1 xoffset=0 yoffset=0 xadvance=1 page=0 chnl=15$1"),
                            false, "UTF-8");
                }
            }
        }
    }
}
